#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const dir = path.resolve(__dirname, "..")
const opencodeDir = path.resolve(dir, "../opencode")

process.chdir(dir)

// ── Models snapshot ──────────────────────────────────────────────────────────
const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

await Bun.write(
  path.join(opencodeDir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(opencodeDir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")

// ── Migrations ───────────────────────────────────────────────────────────────
const migrationDirs = (
  await fs.promises.readdir(path.join(opencodeDir, "migration"), { withFileTypes: true })
)
  .filter((e) => e.isDirectory() && /^\d{14}/.test(e.name))
  .map((e) => e.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(opencodeDir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(+match[1], +match[2] - 1, +match[3], +match[4], +match[5], +match[6])
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

// ── Version ──────────────────────────────────────────────────────────────────
const rootPkg = await Bun.file(path.resolve(dir, "../../package.json")).json()
const version: string = process.env.OPENCODE_VERSION ?? rootPkg.version ?? "0.0.0"
const channel: string = process.env.OPENCODE_CHANNEL ?? "local"

// ── Build flags ──────────────────────────────────────────────────────────────
const singleFlag = process.argv.includes("--single")
const prodFlag = process.argv.includes("--production") || process.env.NODE_ENV === "production"

const allTargets: { os: string; arch: "arm64" | "x64"; abi?: "musl" }[] = [
  { os: "linux", arch: "arm64" },
  { os: "linux", arch: "x64" },
  { os: "linux", arch: "arm64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl" },
  { os: "darwin", arch: "arm64" },
  { os: "darwin", arch: "x64" },
]

const targets = singleFlag
  ? allTargets.filter((t) => t.os === process.platform && t.arch === process.arch && !t.abi)
  : allTargets

await $`rm -rf dist`

for (const item of targets) {
  const name = ["opencode-server", item.os === "win32" ? "windows" : item.os, item.arch, item.abi]
    .filter(Boolean)
    .join("-")

  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  await Bun.build({
    tsconfig: path.join(opencodeDir, "tsconfig.json"),
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace("opencode-server", "bun") as any,
      outfile: `dist/${name}/bin/opencode-server`,
      execArgv: [`--user-agent=opencode-server/${version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/main.ts"],
    format: prodFlag ? "esm" : undefined,
    bytecode: prodFlag,
    define: {
      OPENCODE_VERSION: `'${version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OPENCODE_CHANNEL: `'${channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  if (item.os === process.platform && item.arch === process.arch && !item.abi) {
    const bin = `dist/${name}/bin/opencode-server`
    console.log(`Smoke test: ${bin} --version`)
    try {
      const out = await $`${bin} --version`.text()
      console.log(`OK: ${out.trim()}`)
    } catch (e) {
      console.error(`Smoke test failed:`, e)
      process.exit(1)
    }
  }
}

console.log("Done.")
